name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-vue-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
      
    - name: Install Yarn
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: Run Lint
      run: npm run lint